version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  build_and_push_docker_image: # TODO: tag docker imgs for envs / caching
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build and push Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/adventure-frontend:$CIRCLE_SHA1 .
            docker push $DOCKER_USERNAME/adventure-frontend:$CIRCLE_SHA1

  test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results

  deploy-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Create terraform.tfvars for Test
          command: |
            echo "ami_id = \"$TEST_AMI_ID\"" > terraform.tfvars
            echo "image_tag = \"$DOCKER_USERNAME/adventure-frontend:$CIRCLE_SHA1\"" >> terraform.tfvars
            echo "key_name = \"$KEY_NAME\"" >> terraform.tfvars
      - run:
          name: Deploy to Test environment
          command: |
            terraform init
            terraform workspace select test
            terraform apply -auto-approve -var-file="terraform.tfvars"

  deploy-prod:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Create terraform.tfvars for Prod
          command: |
            echo "ami_id = \"$PROD_AMI_ID\"" > terraform.tfvars
            echo "image_tag = \"$DOCKER_USERNAME/adventure-frontend:$CIRCLE_SHA1\"" >> terraform.tfvars
            echo "key_name = \"$KEY_NAME\"" >> terraform.tfvars
      - run:
          name: Deploy to Prod Environment
          command: |
            terraform init
            terraform workspace select prod
            terraform apply -auto-approve -var-file="terraform.tfvars"

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build_and_push_docker_image:
          requires:
            - test
      - deploy-test:
          requires:
            - test
      - deploy-prod:
          requires:
            - deploy-test
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
